services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ../ssl:/app/ssl
      - ui_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    container_name: frontend-dev

volumes:
  ui_node_modules:
